/** Re-exports for Coach teaching video (watch-only, single timeline). */

export {
  buildCoachLessonSettings,
  COACH_CAPTURE_SPEECH_DELAY_MS,
  COACH_LESSON_BOARD_ID,
  COACH_MOVE_BANNER_HOLD_MS,
  COACH_MOVE_SPEECH_DELAY_MS,
  COACH_POST_DEMO_PAUSE_MS,
  COACH_SEGMENT_BANNER_HOLD_MS,
  COACH_SEGMENT_SPEECH_DELAY_MS,
  COACH_VIDEO,
  COACH_VIDEO_BOARD_ID,
  COACH_VIDEO_BASICS_END_MS,
  COACH_VIDEO_DURATION_MS,
  COACH_VIDEO_SEGMENT_BANNERS,
  COACH_VIDEO_SEGMENT_STARTS_MS,
  coachSpeechForTime,
  coachBannerHoldMs,
  findCoachCueAtTime,
  COACH_VIDEO_TRIPLE_SPEECH_TEXT,
  COACH_VIDEO_WIN_SEGMENT_START_MS,
  coachSegmentBannerUntilMs,
  findCoachSegmentBannerAtTime,
  formatCoachTime,
  findCoachKeyframeAt,
  findCoachKeyframeAfterMove,
  findCoachKeyframeByTime,
  type CoachLessonStepSettings,
  type CoachVideoCue,
  type CoachVideoHighlight,
  type CoachVideoSegmentBanner,
  type CoachVideoKeyframe,
  type CoachVideoMove,
  type CoachVideoScript,
  type CoachVideoSpeech,
} from './CoachVideoScript';
